import type { Metadata } from "next";
// Removed Next.js font loader imports. Using custom font (IranSans) only.
import "./styles/globals.scss";
import "./styles/variables.scss";
import "./styles/main.scss";

export const metadata: Metadata = {
  title: "Create houk App",
  description: "Generated by create houk app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
